---
title: "Fig5"
author: "Lyu"
date: "7/20/2022"
output: html_document
---

```{r}
library(tidyverse)
library(scales)
library(ggpubr)
```

```{r frequencyCV WT Fig5c}
megRAND_TAD_wt <- readRDS('./input/WT_frequencyCV_TADvsBoundaryvsControl.rds')

my_comparisons <- list( c("TAD", "RANDOM"), c("RANDOM", "TADboundary") )
p <- megRAND_TAD_wt %>% ggplot(aes(x=type,y=FreqCV,color=type))+
  geom_boxplot(lwd=0.25,outlier.colour = NA, width=0.75, fatten=1)+
  #stat_summary(fun=mean, geom="point", shape=20, size=4, color="red", fill="red") +
  stat_compare_means(comparisons =my_comparisons,size=2)+
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position='none',
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.background=element_blank(),
    strip.text=element_text(size=7))+
  xlab("")+
  ylab("FrequencyCV(median)")
ggsave(filename = "FrequencyCV_wt.pdf",plot = p,width=90,height = 45,units = "mm", dpi = 300)

```

```{r frequencyCV SCC4 Fig5d }
megRAND_TAD_scc <- readRDS('./input/SCC_frequencyCV_TADvsBoundaryvsControl.rds')

my_comparisons <- list( c("TAD", "RANDOM"), c("RANDOM", "TADboundary") )
p <- megRAND_TAD_scc %>% ggplot(aes(x=type,y=FreqCV,color=type))+
  geom_boxplot(lwd=0.25,outlier.colour = NA, width=0.75, fatten=1)+
  #stat_summary(fun=mean, geom="point", shape=20, size=4, color="red", fill="red") +
  stat_compare_means(comparisons =my_comparisons,size=2)+
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position='none',
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.background=element_blank(),
    strip.text=element_text(size=7))+
  xlab("")+
  ylab("FrequencyCV(median)")
ggsave(filename = "FrequencyCV_scc.pdf",plot = p,width=90,height = 45,units = "mm", dpi = 300)
```

```{r SPM of gene coexpression WT Fig6b}
wt_spm <- readRDS('./input/wt_coexpression_spm.rds')
wt_spm_median <- readRDS('./input/wt_coexpression_spm_median.rds')
p <- ggplot(wt_spm,aes(x=cor,color=type))+
  geom_density(size=0.25)+
  #stat_compare_means(comparisons = my_comparisons)+
  geom_vline(data=wt_spm_median,aes(xintercept=med, color=type),
             linetype="dashed")+
  theme_man+
  theme(legend.position = c(0.15, 0.8),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.text = element_text(size=6))+
  xlim(-0.2,0.2)+
  ylab('density')+
  xlab("Spearman r")+
  annotate(geom="text",x=0.2, y=4, label="WT",size=2)
  
ggsave(filename = "spearmanR_wt.pdf",plot = p,width=90,height = 45,units = "mm", dpi = 300)
```

```{r SPM of gene coexpression SCC4KO Fig6b}
scc_spm <- readRDS('./input/scc_coexpression_spm.rds')
scc_spm_median <- readRDS('./input/scc_coexpression_spm_median.rds')
p <- ggplot(scc_spm,aes(x=cor,color=type))+
  geom_density(size=0.25)+
  #stat_compare_means(comparisons = my_comparisons)+
  geom_vline(data=scc_spm_median,aes(xintercept=med, color=type),
             linetype="dashed")+
  theme_man+
  theme(legend.position = c(0.15, 0.8),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.text = element_text(size=6))+
  xlim(-0.2,0.2)+
  xlab("Spearman r")+
  ylab('density')+
  annotate(geom="text",x=0.2, y=4, label="SCC4-/-",size=2)
ggsave(filename = "spearmanR_scc.pdf",plot = p,width=90,height = 45,units = "mm", dpi = 300)
```

```{r new fig5 c}
library(tidyverse)
library(ggpubr)
#pairwise comparison

saveRDS(megRAND_TAD_vs_control,file = 'WT_frequencyCV_TADvsControl.rds')
saveRDS(megRAND_TAD_vs_boundary,file = 'WT_fsizeCV_TADvsBoundary.rds')

megRAND_TAD_vs_control <- readRDS('./input/WT_frequencyCV_TADvsControl.rds')
megRAND_TAD_vs_boundary <- readRDS('./input/WT_frequencyCV_TADvsBoudary.rds')
#plot noiseCV
my_comparisons <- list( c("TAD", "RANDOM")) #, c("RANDOM", "TADboundary") 
p <- megRAND_TAD_vs_control %>% ggplot(aes(x=type,y=FreqCV,color=type))+
  geom_boxplot(lwd=0.25,outlier.colour = NA, width=0.75, fatten=1)+
  #stat_summary(fun=mean, geom="point", shape=20, size=4, color="red", fill="red") +
  stat_compare_means(comparisons =my_comparisons,size=2)+
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position='none',
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.background=element_blank(),
    strip.text=element_text(size=7))+
  xlab("")+
  ylab("FrequencyCV")
ggsave(filename = "FrequencyCV_TADvsControl_wt.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)

#TADs vs boundary
my_comparisons <- list( c("TAD", "TADboundary")) 
p <- megRAND_TAD_vs_boundary %>% ggplot(aes(x=type,y=FreqCV,color=type))+
  geom_boxplot(lwd=0.25,outlier.colour = NA, width=0.75, fatten=1)+
  #stat_summary(fun=mean, geom="point", shape=20, size=4, color="red", fill="red") +
  stat_compare_means(comparisons =my_comparisons,size=2)+
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position='none',
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.background=element_blank(),
    strip.text=element_text(size=7))+
  xlab("")+
  ylab("FrequencyCV")
ggsave(filename = "FrequencyCV_TADvsBoundary_wt.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)

```

