---
title: "Supplementary Fig4"
author: "Lyu"
date: "7/18/2022"
output: html_document
---

```{r load library}
library(tidyverse)
library(scales)

```

```{r venn SF 4a}
ERCCrm <- readRDS('./input/LAST_on_RNA.rds')
twolysate <- ERCCrm[,1:2]
colSums(twolysate>0)
twolysateover <-  twolysate[rowSums(twolysate>0)>1,] #8281

library(VennDiagram)

# move to new plotting page
grid.newpage()

# create pairwise Venn diagram
p <- draw.pairwise.venn(area1 = 10132,                        # Create pairwise venn diagram
                   area2 = 10210,
                   cross.area = 8281,
                   lwd = 1,
                   cex = .6)

ggsave(filename = "Venn.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)

```

```{r RNA sample correlation SF 4b}
library(corrplot)
M <- readRDS('./input/RNAsamplecorrelation.rds')
corrplot(M, method = 'number')
```

```{r reads coverage information from RSeQC SF 4c}
cell1 <- read.delim('./input/output1.geneBodyCoverage.txt',header = F)
rownames(cell1) <- cell1$V1
cell1$V1 <- NULL
cell1 <-as.data.frame(t(cell1)) 
totalreads <-sum(cell1[,2]) 
cell1$rate <- cell1$Cell1_sorted/totalreads
cell1$type <- rep('cell1',100)
cell1$Cell1_sorted <- NULL

cell2 <- read.delim('./input/output2.geneBodyCoverage.txt',header = F)
rownames(cell2) <- cell2$V1
cell2$V1 <- NULL
cell2 <-as.data.frame(t(cell2)) 
totalreads <-sum(cell2[,2]) 
cell2$rate <- cell2$Cell2_sorted/totalreads
cell2$type <- rep('cell2',100)
cell2$Cell2_sorted <- NULL

cell3 <- read.delim('./input/output3.geneBodyCoverage.txt',header = F)
rownames(cell3) <- cell3$V1
cell3$V1 <- NULL
cell3 <-as.data.frame(t(cell3)) 
totalreads <-sum(cell3[,2]) 
cell3$rate <- cell3$Cell3_sorted/totalreads
cell3$type <- rep('cell3',100)
cell3$Cell3_sorted <- NULL

cellALL <-as.data.frame(rbind(cell1,cell2,cell3)) 

#plot distribution
p <- ggplot(cellALL, aes(x=Percentile,y=rate,color=type))+
  geom_line(size=0.25)+
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.background=element_blank(),
    strip.text=element_text(size=7))+
  xlab("gene body percentile (5'=>3')")+
  ylab("Coverage")+
  theme(legend.position = c(0.1, 0.9),
        legend.key.size = unit(0.1, "cm"),
        legend.key.width = unit(0.1, "cm"),
        legend.text = element_text(size=5))

ggsave(filename = "coverage.pdf",plot = p,width=45*1.5,height = 45,units = "mm", dpi = 300) 
```

```{r LAST-seq vs CELLss read SF 4d}
cel_reads <- readRDS('./input/celss_1M_reads.rds')
cel_read <- cel_reads[!grepl('^ERCC-',rownames(cel_reads)),]
meanreadscel <-as.data.frame(rowSums(cel_read)/10) 
colnames(meanreadscel) <- 'meanreadscel'
meanreadscel$ID <- rownames(meanreadscel)

last_read1 <- readRDS('./input/LAST_read1_1M.rds')
lastmeadreads <- as.data.frame(rowSums(last_read1[1:10])/10)
colnames(lastmeadreads) <- 'meadreads'
lastmeadreads$ID <- rownames(lastmeadreads)


last_cel_reads <- inner_join(lastmeadreads,meanreadscel,by='ID')
last_cel_reads <- last_cel_reads %>%
  filter(meadreads>1 & meanreadscel > 1)

#random sample 2000 genes for plotting
RN <- nrow(last_cel_reads)
RS <- sample (RN, size=2000, replace =F)
last_cel_readsR <- last_cel_reads[RS,]

p <-last_cel_readsR%>% ggplot(aes(x=meadreads, y= meanreadscel))+
  geom_point(size=0.1)+
  #remove background
  theme_man+
  scale_x_log10(limits= c(1, 30000)) +
  scale_y_log10(limits= c(1, 30000)) +
  annotation_logticks(sides = "bl", size=0.15, short = unit(0.05, "cm"), mid = unit(0.1, "cm"), long = unit(0.15, "cm")) +
  annotate(geom="text",x=5, y=30000, label="PCC=0.708",size=2)+
  #xlim(0, 9)+
  #ylim(0.1, 10000)+
  #change x and y labels
  xlab("LAST-seq read numbers")+  
  ylab("CEL-seq2 read numbers")
cor(log10(last_cel_reads$meadreads),log10(last_cel_reads$meanreadscel),method = 'pearson')
ggsave(filename = "LAST_CELss_reads_genes_1.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)
```

```{r LAST-seq vs CELLss UMI SF 4e }

celss <- readRDS('./input/celss_1M.rds')
cellssrm <-na.omit(as.data.frame( celss[!grepl('^ERCC-',rownames(celss)),])) 
cel_UMI_1MM <- as.data.frame(rowSums(cellssrm)/10)
colnames(cel_UMI_1MM) <- 'meanreadsCEL'
cel_UMI_1MM$ID <- rownames(cel_UMI_1MM)

last_UMI_1M_1A <-as.data.frame(readRDS('./input/last_UMI_1M_1.rds'))
last_UMI_1M_1 <- last_UMI_1M_1A[!grepl('^ERCC-',rownames(last_UMI_1M_1A)),]
last_UMI_1 <- last_UMI_1M_1
last_UMI_1MM <- as.data.frame(rowSums(last_UMI_1)/10)
colnames(last_UMI_1MM ) <- 'meanreadsLAST'
last_UMI_1MM$ID <- rownames(last_UMI_1MM)

LAST_CEL_UMI <- inner_join(last_UMI_1MM,cel_UMI_1MM,by='ID')

LAST_CEL_UMI <- LAST_CEL_UMI %>%
  filter(meanreadsCEL>0.2 & meanreadsLAST>0.2)

#saveRDS(LAST_CEL_UMI,file = 'LAST_CEL_UMI_1M.rds')

#random sample 2000 genes for plotting
RN <- nrow(LAST_CEL_UMI)
RS <- sample (RN, size=2000, replace =F)
LAST_CEL_UMIR <- LAST_CEL_UMI[RS,]

p <-LAST_CEL_UMIR%>% ggplot(aes(x=meanreadsLAST, y= meanreadsCEL))+
  geom_point(size=0.1)+
  #remove background
  theme_man+
  scale_x_log10(limits= c(1, 10000)) +
  scale_y_log10(limits= c(1, 10000)) +
  annotation_logticks(sides = "bl", size=0.15, short = unit(0.05, "cm"), mid = unit(0.1, "cm"), long = unit(0.15, "cm")) +
  annotate(geom="text",x=5, y=10000, label="PCC=0.762",size=2)+
  #xlim(0, 9)+
  #ylim(0.1, 10000)+
  #change x and y labels
  xlab("LAST-seq UMI numbers")+  
  ylab("CEL-seq2 UMI numbers")
cor(log10(LAST_CEL_UMI$meanreadsLAST),log10(LAST_CEL_UMI$meanreadsCEL),method = 'pearson')
ggsave(filename = "LAST_CELss_UMI_genes.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)
```

```{r LAST-seq vs SMART-seq reads SF 4f}
last_read1 <- readRDS('./input/LAST_read1_1M.rds')
lastmeadreads <- as.data.frame(rowSums(last_read1[1:10])/10)
colnames(lastmeadreads) <- 'lastmeadreads'
lastmeadreads$ID <- rownames(lastmeadreads)

SMARTfull<- readRDS('./input/SMART_reads_1M.rds')
meanreadssmart <-as.data.frame(rowSums(SMARTfull)/9) 
colnames(meanreadssmart) <- 'meanreadssmart'
meanreadssmart$ID <- rownames(meanreadssmart)

last_smart_reads <- inner_join(lastmeadreads,meanreadssmart,by='ID')
last_smart_reads <- last_smart_reads %>%
  filter(lastmeadreads>1&meanreadssmart>1)

#random sample 2000 genes for plotting
RN <- nrow(last_smart_reads)
RS <- sample (RN, size=2000, replace =F)
last_smart_readsR <- last_smart_reads[RS,]


p <-last_smart_readsR%>% ggplot(aes(x=lastmeadreads, y= meanreadssmart))+
  geom_point(size=0.1)+
  theme_man+
  scale_x_log10(limits= c(1, 30000)) +
  scale_y_log10(limits= c(1, 30000)) +
  annotation_logticks(sides = "bl", size=0.15, short = unit(0.05, "cm"), mid = unit(0.1, "cm"), long = unit(0.15, "cm")) +
  annotate(geom="text",x=5, y=30000, label="PCC=0.620",size=2)+
  xlab("LAST-seq read numbers")+  
  ylab("SMART-seq reads numbers")
cor(log10(last_smart_reads$lastmeadreads),log10(last_smart_reads$meanreadssmart),method = 'pearson')
ggsave(filename = "LAST_SMARTFULL_reads_genes.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)
```

```{r library size SF8c}
librarysize <- readRDS('./input/librarysize.rds')
p <- librarysize %>% ggplot(aes(x=Size,y=Conc.))+
  geom_point(size=.1)+
  geom_line(size=.25)+
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.background=element_blank(),
    strip.text=element_text(size=7))+
  scale_x_continuous(limits = c(0,800),
                     breaks = seq(0,800,100))+
  xlab("gene coding region (bp)")+
  ylab("Intensity (A.U.)")

ggsave(filename = "fragmentsize.pdf",plot = p,width=90,height = 45,units = "mm", dpi = 300)
```

